# Generated by Django 4.1.7 on 2023-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittermessages',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
